### ISSUE TITLE
Questions about how the api call is realized

### ISSUE THREAD

**Issue by Skyorca** [jwzhanggy/Graph_Toolformer#1]
Hi, your work is really eyes-catching and I really like it. However, some key questions confuse me:
1. Is the api call <API>XXXX</API> realized by some package like networkx?
2. How the LLM know about the graph structure? Do you input the graph structure to LLM after loading it?
3. Here is my understanding of your work, is it correct or not? During training, such model teaches LLM to translate natural language query to graph api and utilizes outer tools to compute and return results as api callback. Thus, LLM has the ability to infer on complex. structured graph data.
Thanks a lot for your reply :)

**Comment by jwzhanggy** [comment]
1. graph property api is implemented with networkx, other reasoning tasks will use different gnn/graph models to implement the apis.
2. we define GL(graph_data) api call for loading the graph data, and LLMs will detect the graph data to be loaded.
3. your understanding is correct based on the current version.

**Comment by RManLuo** [comment]
Hi @jwzhanggy, thanks for sharing your interesting works. I have a similar question about the api call. 

After loading the graph using API, how to input the graph into LLMs? Do you input the graph structure by a sequence of nodes/edges?

**Comment by jwzhanggy** [comment]
it depends on the graph structure and reasoning task, either load the complete graph, or load the subgraph, or load the sequence of nodes/edges. In the current first version, as long as the data transmission interface between the Graph_Loading() API and Graph_Reasoning() API communicates well with each other, then it will be good.

**Comment by RManLuo** [comment]
> it depends on the graph structure and reasoning task, either load the complete graph, or load the subgraph, or load the sequence of nodes/edges. In the current first version, as long as the data transmission interface between the Graph_Loading() API and Graph_Reasoning() API communicates well with each other, then it will be good.

Thanks for your reply. I understand the pipeline now!
