### ISSUE TITLE
Question about prompt data format 

### ISSUE THREAD

**Issue by Tebmer** [jwzhanggy/Graph_Toolformer#3]
Hi, this is a really awesome work! 

I have a question about the format of prompt data. 

The relationship between output and input is that "the **output** will **repeat** the **input**, and also insert the API call at the most appropriate position.", just like the following sample:
```
Input: In the context of the citeseer bibliographic network, paper #2722 is dedicated to the study of [TBR]. 
Output: In the context of the citeseer bibliographic network, paper #2722 is dedicated to the study of [GR(GL("citeseer"), "graph_bert:topic", paper#2722)-->r]. 
Reasoning Result: DB.
```

However, I found some prompt data you provide where the output dose not repeat the input , like
```
Input: What is the topic of paper #3230 in the citeseer bibliographic network? 
Output: The topic of paper #3230 in the citeseer bibliographic network is [GR(GL("citeseer"), "graph_bert:topic", paper#3230)-->r]. 
Reasoning Result: ML.
```

How to understand that? Thanks a lot for your reply.

**Comment by jwzhanggy** [comment]
we add that to make graph-toolformer can also handle the basic Q&A for graph reasoning.

**Comment by Tebmer** [comment]
Thanks for your reply!

But according to Section 4.5 "LLMs Fine-Tuning for Graph Reasoning" in your paper, the API is inserted to the `Input`, so dose that mean the content of `Input` cannot be modified?

I also read your code about generation of `Output`, but I don't find the corresponding code snippet of `4.5.1 API Call Insertion Position Prediction.`.

So, I infer that the `Output` is just the generation result of the LLM?

**Comment by jwzhanggy** [comment]
Yes, graph-toolformer can handle different inputs now. we are updating the paper to reflect these changes, will release the updated paper shortly.
