### ISSUE TITLE
from koala.graph_models.toolx.Toolx import Toolx ModuleNotFoundError: No module named 'koala.graph_models'

### ISSUE THREAD

**Issue by beena1472** [jwzhanggy/Graph_Toolformer#7]

**Comment by jwzhanggy** [comment]
see this page https://github.com/jwzhanggy/Graph_Toolformer/tree/main/Graph_Toolformer_Package/koala

**Comment by beena1472** [comment]
I download bith the zip files and placed them in language and graph models
but still show the error that module not found.
